#!/usr/bin/env bash
# Redirect to another page
apt-get -y update
apt-get -y install nginx
sudo chown -R ubuntu:ubuntu /var/www
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me http://www.youtube.com permanent;" /etc/nginx/sites-available/default
service nginx start
