#!/usr/bin/env bash
# update and install nginx
# nginx
sudo apt-get -y update
sudo apt-get -y install nginx
hostname=$(cat /etc/hostname)
sudo sed -i "37 i\ \tadd_header X-Served-By $hostname;\n" /etc/nginx/sites-enabled/default
sudo service nginx restart