#!/usr/bin/env bash
# install Goole
apt-get-repository ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get install haproxy
echo -e "listen 1125-lb-01\n\tbind *:80\n\tstats enable\n\tbalance roundrobin\n\tserver 1125-web-01 35.227.27.183 check\n\tserver 1125-web-02 34.74.72.60:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart