#!/usr/bin/env bash
#condition message
count=0
while [ $((count++)) -lt 20 ]; do
	echo $count
	case $count in 4)
		echo bad luck from China
		;;
	9)
		echo bad luck from Japan
		;;
	17)
		echo bad luck from Italy
		;;
	esac
done
